import turtle
turtle.penup()
turtle.goto(0,-200)
turtle.pendown()
turtle.circle(200)

turtle.penup()
turtle.goto(-100,50)
turtle.pendown()
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

turtle.penup()
turtle.goto(100,50)
turtle.pendown()
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

turtle.penup()
turtle.goto(0,50)
turtle.pendown()
turtle.circle(-80,steps=3)

turtle.penup()
turtle.goto(-130,-70)
turtle.pendown()
turtle.goto(0,-130)
turtle.goto(130,-70)
turtle.hideturtle()
turtle.done()